USE DATABASE LAZBOY_SUPPLY_CHAIN_DB;
USE SCHEMA BRONZE;

COPY INTO DIM_PRODUCT_RAW
FROM @S3_LAZBOY_STAGE/dim_product.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_SUPPLIER_RAW
FROM @S3_LAZBOY_STAGE/dim_supplier.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO DIM_WAREHOUSE_RAW
FROM @S3_LAZBOY_STAGE/dim_warehouse.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO FACT_INVENTORY_TRANSACTIONS
FROM @S3_LAZBOY_STAGE/fact_inventory_transactions.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
