USE DATABASE LAZBOY_SUPPLY_CHAIN_DB;
USE SCHEMA SILVER;

CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT
    PRODUCT_ID,
    SKU,
    PRODUCT_NAME,
    CATEGORY,
    SUBCATEGORY,
    UNIT_COST,
    DEFECT_FLAG,
    RETURN_REASON
FROM LAZBOY_SUPPLY_CHAIN_DB.BRONZE.DIM_PRODUCT_RAW;

CREATE OR REPLACE TABLE DIM_SUPPLIER AS
SELECT
    SUPPLIER_ID,
    SUPPLIER_NAME,
    COUNTRY,
    REGION,
    LEAD_TIME_DAYS,
    SUPPLIER_TYPE,
    SUPPLIER_CITY,
    SUPPLIER_STATE
FROM LAZBOY_SUPPLY_CHAIN_DB.BRONZE.DIM_SUPPLIER_RAW;

CREATE OR REPLACE TABLE DIM_WAREHOUSE AS
SELECT
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    WAREHOUSE_CITY,
    WAREHOUSE_STATE,
    REGION,
    CAPACITY_UNITS
FROM LAZBOY_SUPPLY_CHAIN_DB.BRONZE.DIM_WAREHOUSE_RAW;

CREATE OR REPLACE TABLE FACT_INVENTORY_TRANSACTIONS_CLEAN AS
SELECT
    TRANSACTION_ID,
    DATE_ID,
    PRODUCT_ID,
    SUPPLIER_ID,
    WAREHOUSE_ID,
    TRANSACTION_TYPE,
    QUANTITY,
    UNIT_COST,
    ACTUAL_LEAD_DAYS,
    RETURN_DEFECT_FLAG,
    NOTES
FROM LAZBOY_SUPPLY_CHAIN_DB.BRONZE.FACT_INVENTORY_TRANSACTIONS;
