USE DATABASE LAZBOY_SUPPLY_CHAIN_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE INVENTORY_ANALYTICS AS
SELECT
    f.*,
    p.SKU,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUBCATEGORY,
    p.UNIT_COST AS PRODUCT_UNIT_COST,
    p.DEFECT_FLAG,
    p.RETURN_REASON,
    s.SUPPLIER_NAME,
    s.COUNTRY,
    s.LEAD_TIME_DAYS,
    s.SUPPLIER_TYPE,
    s.SUPPLIER_CITY,
    s.SUPPLIER_STATE,
    w.WAREHOUSE_NAME,
    w.WAREHOUSE_CITY,
    w.WAREHOUSE_STATE,
    w.REGION AS WAREHOUSE_REGION,
    w.CAPACITY_UNITS,
    (f.QUANTITY * f.UNIT_COST) AS TOTAL_COST
FROM LAZBOY_SUPPLY_CHAIN_DB.SILVER.FACT_INVENTORY_TRANSACTIONS_CLEAN f
LEFT JOIN LAZBOY_SUPPLY_CHAIN_DB.SILVER.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN LAZBOY_SUPPLY_CHAIN_DB.SILVER.DIM_SUPPLIER s
    ON f.SUPPLIER_ID = s.SUPPLIER_ID
LEFT JOIN LAZBOY_SUPPLY_CHAIN_DB.SILVER.DIM_WAREHOUSE w
    ON f.WAREHOUSE_ID = w.WAREHOUSE_ID;
